version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: alove
      POSTGRES_USER: alove
      POSTGRES_PASSWORD: alove
    ports: [ "5432:5432" ]
    volumes:
      - alove_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports: [ "6379:6379" ]
    volumes:
      - alove_redis:/data

  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_ENV: "development"
      MEILI_MASTER_KEY: "dev-master-key"
    ports: [ "7700:7700" ]
    volumes:
      - alove_meili:/meili_data

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: alove
      MINIO_ROOT_PASSWORD: alovealove
    ports: [ "9000:9000", "9001:9001" ]
    volumes:
      - alove_minio:/data

  api:
    build: ./apps/api
    env_file: ./apps/api/.env.development
    depends_on: [ db, redis, meilisearch, minio ]
    ports: [ "3001:3001" ]
    volumes:
      - ./apps/api:/usr/src/app
    command: npm run start:dev

  web:
    build: ./apps/web
    env_file: ./apps/web/.env.development
    depends_on: [ api ]
    ports: [ "3000:3000" ]
    volumes:
      - ./apps/web:/usr/src/app
    command: npm run dev

volumes:
  alove_pg:
  alove_redis:
  alove_meili:
  alove_minio:
