FROM node:20-alpine
RUN apk add --no-cache openssl libc6-compat python3 make g++
WORKDIR /usr/src/app
COPY package.json package-lock.json* ./
RUN npm ci || npm i
EXPOSE 3001
CMD ["npm", "run", "start:dev"]
